graph LR
  linkStyle default fill:#ffffff

  subgraph diagram [Host - Containers]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 2 [Host]
      style 2 fill:#ffffff,stroke:#365615,color:#365615

      3("<div style='font-weight: bold'>Docker</div><div style='font-size: 70%; margin-top: 0px'>[Container: Docker]</div><div style='font-size: 80%; margin-top:10px'>A container framework</div>")
      style 3 fill:#ffffff,stroke:#341a6e,color:#341a6e
      4("<div style='font-weight: bold'>Storage</div><div style='font-size: 70%; margin-top: 0px'>[Container: Disk]</div><div style='font-size: 80%; margin-top:10px'>SSD at /home/$USER/tv</div>")
      style 4 fill:#ffffff,stroke:#76bc2d,color:#76bc2d
    end

  end